<?php 
function pippin_stripe_process_payment() {
	if(isset($_POST['action']) && $_POST['action'] == 'stripe' && wp_verify_nonce($_POST['stripe_nonce'], 'stripe-nonce')) {
 		
 		/**
		 * "Stripe" Data Setup
		 */
		global $stripe_options;
 
		// load the stripe libraries
		require_once(get_stylesheet_directory() . '/lib/Stripe.php');
 
		// retrieve the token generated by stripe.js
		$token = $_POST['stripeToken'];
		// retrieve product description
		$desc = $_POST['description'];

		/*
	 	 * Calculate total amount server side (based on description format)
	   */
		$subtotal = 0;
		$desiredProducts = explode('|', $desc);
		foreach ($desiredProducts as $desiredProduct) {
			$desiredProductValues = explode(',',$desiredProduct);
			foreach ($desiredProductValues as $key => $value) {
				// Returns PostID
				if($key == 0) {
				$productPrice = get_field('product_price', $value); // Individual product price
				}
				// Returns Quantity
				if($key == 3) {
				$quantity = $value;
				}
				$temp = $productPrice * $quantity; // For each product, calculate total cost before tax
			}
			$subtotal += $temp; // Add each product total to the subtotal
		}
		$tax = round($subtotal * 0.0471); // Round tax to an integer (rounds up after .5)
		$grandtotal = $subtotal + $tax;

		// set the total amount in cents
		$amount = $grandtotal;
 
		// check if we are using test mode
		if(isset($stripe_options['test_mode']) && $stripe_options['test_mode']) {
			$secret_key = $stripe_options['test_secret_key'];
		} else {
			$secret_key = $stripe_options['live_secret_key'];
		}
 		
 		Stripe::setApiKey($secret_key);

		/**
		 * "Charging the Card"
		 */
		try {

			// Grab user's customer ID...
			if( is_user_logged_in() ):
				global $current_user;
				get_currentuserinfo();
				$customer_id = get_user_meta( get_current_user_id(), '_stripe_customer_id', true );
				$customer_email = $current_user->user_email;
			else:
				$customer_id = false;
			endif;

			// create a new customer if our current user doesn't have one...
			if( !$customer_id ) {
				$customer = Stripe_Customer::create(array(
					'card' => $token,
					'email' => $customer_email
				));
			
				$customer_id = $customer->id;
			 
				if( is_user_logged_in () ) {
					update_user_meta( get_current_user_id(), '_stripe_customer_id', $customer_id );
				}
			}

			// charge customer if an customer id is found is found
			if( $customer_id ) {
				$charge = Stripe_Charge::create(array(
					'amount' => $amount, // amount in cents
					'currency' => 'usd',
					'customer' => $customer_id,
					'description' => $desc
				));
			} else {
				// the customer wasn't found or created, throw an error
				throw new Exception( __( 'A customer could not be created, or no customer was found.', 'litton_bags' ) );
			}

			// redirect on successful payment
			$redirect = add_query_arg('payment', 'paid', $_POST['redirect']);
 
		} catch (Exception $e) {
			// redirect on failed payment
			$redirect = add_query_arg('payment', 'failed', $_POST['redirect']);
		}
 
		// redirect back to our previous page with the added query variable
		wp_redirect($redirect); exit;
	}
}
add_action('init', 'pippin_stripe_process_payment');
?>